### ISSUE TITLE
Cannot connect to 2181 from my java code

### ISSUE THREAD

**Issue by ctyeh** [smizy/docker-apache-phoenix#4]
Hi, thanks for your efforts. I try to connect to zookeeper with my Hbase java code, but always got "com.google.protobuf.ServiceException: java.net.ConnectException: Connection refused".  I added     ports:  ["2181:2181"] into section "zookeeper-1" of docker-compose.yml, but didn't work. Is there any way to solve this problem?

**Comment by viniciusboson** [comment]
Hi, I'm having the same problem! Even exposing the 2181 port for zookeeper I'm not able to connect to it.
```
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_192]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_192]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
```

Any luck on that ?
